services:
  postgres:
    image: postgres:16
    container_name: orders-postgres
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - orders-postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: orders-rabbitmq
    ports:
      - "5672:5672"       # porta para conexões AMQP
      - "15672:15672"     # porta para console de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  orders-postgres-data:
