spring.application.name=eureka-server

# Desabilitar completamente o Config Client
spring.cloud.config.enabled=false

# --- SERVER ---
server.port=8761

# --- EUREKA SERVER ---
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

# --- LOGGING ---
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO

# --- ACTUATOR ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always